github: [metadata]
kramdown:
 input: GFM
 hard_wrap: false
permalink: /:categories/:year/:month/:day/:title
url: https://sunderb.github.io/community-hub-website
gems:
   - jekyll-coffeescript
   - jekyll-paginate
   - jekyll-redirect-from
